name: gandalf
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  share: 0.6.5+2
  provider: 4.3.2+2
  url_launcher: 5.4.1
  flutter_icons: 1.1.0

  admob_flutter: 1.0.0
  firebase_core: 0.5.0
  in_app_purchase: 0.3.4+12
  firebase_analytics: 6.0.0
  firebase_performance: 0.4.0
  firebase_crashlytics: 0.1.4+1

  video_player: 0.10.11+2

dev_dependencies:
  path: 1.8.0-nullsafety
  yaml: 2.2.1
  io: 0.3.4

flutter_icons:
  includes:
    - mco

flutter:
  uses-material-design: true
  assets:
    - assets/video.mp4
